# Generated by Django 3.0.7 on 2020-08-17 05:32

from django.db import migrations, models
import django.db.models.deletion
import proposals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('openAt', models.DateTimeField()),
                ('closeAt', models.DateTimeField()),
                ('revisionUntil', models.DateTimeField()),
                ('semester', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'proposalsubmission',
                'verbose_name_plural': 'proposalsubmissions',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('titlePersian', models.CharField(max_length=60)),
                ('issuanceDate', models.DateTimeField()),
                ('keywords', models.TextField()),
                ('researchType', models.CharField(choices=[('FU', 'Fundamental'), ('TH', 'Theoretical'), ('PR', 'Practical'), ('DE', 'Developmental')], default='FU', max_length=2)),
                ('defenseDate', models.DateTimeField()),
                ('councilApproved', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=proposals.models.user_directory_path)),
                ('tarifMasale', models.TextField(max_length=5000)),
                ('pishinehPazhuhesh', models.TextField(max_length=5000)),
                ('ruykardHal', models.TextField(max_length=5000)),
                ('premises', models.TextField(max_length=5000)),
                ('jadidBudan', models.TextField(max_length=5000)),
                ('raveshVaAbzar', models.TextField(max_length=5000)),
                ('marajeHami', models.TextField(max_length=5000)),
                ('arbiter1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbiter1', to='users.Professor')),
                ('arbiter2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbiter2', to='users.Professor')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Student')),
            ],
            options={
                'verbose_name': 'proposal',
                'verbose_name_plural': 'proposals',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=5000)),
                ('createdAt', models.DateTimeField()),
                ('commentOn', models.CharField(choices=[('RE', 'Revision'), ('DE', 'Defense')], default='RE', max_length=2)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Professor')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
