# Generated by Django 3.0.7 on 2020-08-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='onProposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.Proposal'),
        ),
    ]
