# Generated by Django 3.0.7 on 2020-08-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20200818_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
